# https://taskfile.dev

version: '3'

includes:
  py:
    taskfile: ./shui-server
    dir: ./shui-server

  js:
    taskfile: ./js
    dir: ./js

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
