# https://taskfile.dev

version: "3"

vars:
  COMPOSE_FILE: docker/docker-compose.yml

tasks:
  format:
    cmds:
      - uv run ruff format
      - uv run ruff check --fix

  code:
    cmds:
      - task: format

  dev:build:
    cmd: docker compose -f {{.COMPOSE_FILE}} --profile stack build

  dev:up:
    cmd: docker compose -f {{.COMPOSE_FILE}} --profile stack up -d

  dev:up:load:
    cmds:
      - task: dev:up
      - uv run docker/file_producer.py main docker/data/catalogs.trig --format application/trig
      - uv run docker/file_producer.py main docker/data/users.trig --format application/trig

  dev:up:load:asb:
    cmds:
      - task: dev:up
      - uv run docker/asb_file_producer.py data/catalogs.trig --format application/trig
      - uv run docker/asb_file_producer.py data/users.trig --format application/trig

  dev:down:
    cmd: docker compose -f {{.COMPOSE_FILE}} --profile stack down

  dev:clean:
    cmd: docker compose -f {{.COMPOSE_FILE}} --profile stack down -v

  dev:query:
    desc: Test connection with a query to Fuseki instance
    cmd: rsparql --service http://localhost:9998/ds --query query.rq

  dev:
    cmd: uv run python src/dev.py

  build:
    cmd: docker build -f docker/Dockerfile -t kg-cms ../
