# https://taskfile.dev

version: '3'

tasks:
  shacl:
    cmds:
      - poetry run pyshacl -s data/shacl.ttl data/catprez.ttl

  test:
    cmd: poetry run pytest -rP

  code:check:
    desc: Check whether code formatting rules apply.
    cmds:
      - poetry run ruff format --check
      - poetry run ruff check

  code:
    desc: Format and standardise code.
    cmds:
      - poetry run ruff format
      - poetry run ruff check --fix
